---

- name: Moto | YUM Install
  import_tasks: yum_install.yml
  tags:
    - moto_install

- name: Moto | MySQL Installation
  import_tasks: mysql_install.yml
  tags:
    - moto_mysql

- name: Moto | MotPoller Setup
  import_tasks: moto_setup.yml
  tags:
    - moto_setup