---

- name: MySQL | Install MySQL Repo
  yum:
    state: latest
    name:
      - http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm

- name: YUM | Update the Hub server
  yum:
    name: "*"
    state: latest

- name: MySQL | Install MySQL Server 
  yum:
    state: latest
    name:
      - python-pip
      - python-setuptools
      - python-wheel 
      - mysql-server

- name: MYSQL | Ansible module pip req
  pip:
    name: pymysql

- name: MySQL | Make sure a service is running
  systemd:
    state: started
    name: mysqld
    daemon_reload: yes
    enabled: yes

- name: Collect all possible information using passwordless root access
  mysql_info:
    login_user: root
