---

- name: YUM | Update the Hub server
  yum:
    name: "*"
    state: latest

- name: YUM - Install a list of required packages
  yum:
    state: latest
    name:
      - perl
      - gcc
      - perl-core
      - net-snmp
      - net-snmp-utils
      - wget
      - cpanminus
      - perl-DBD-MySQL
      #- perl-Net-SNMP
      - dos2unix

- name: YUM | Install Perl CPANM Modules required by MotoPoller
    cpanm:
      name: "{{ item }}"
    loop:
      - CPAN::Meta
      - Net::SNMP
      - SNMP
      - Socket
      - POSIX
      - strict
      - threads
      - Thread::Queue
      - Thread::Semaphore
      - threads::shared
      - warnings
      - Fcntl